### ISSUE TITLE
Minimize use of TimesStamp as Kinesis position 

### ISSUE THREAD

**Issue by itsvikramagr** [qubole/kinesis-sql#3]
We use `timestamp`, as next Kinesis position for next trigger, if there is no new data for a shard in current execution.  Instead of that, can we always use last fetched Sequence Number from earlier triggers? Timestamp might not be unique across records per shards. Less we rely on it, the less would be the chances to make mistakes.

**Comment by OlhaShopback** [comment]
Its also generate random error while Fetching Shard Iterator:
Caused by: org.apache.spark.sql.kinesis.shaded.amazonaws.services.kinesis.model.InvalidArgumentException: The timestampInMillis parameter cannot be greater than the currentTimestampInMillis. timestampInMillis: 1555925802893, currentTimestampInMillis: 1555925802590 (Service: AmazonKinesis; Status Code: 400; Error Code: InvalidArgumentException; Request ID: e5f055d2-fcb9-e4a1-b0c7-d8b8fdc93ab3)

**Comment by itsvikramagr** [comment]
@OlhaShopback - Will soon start the work on this. Implementation for continuous streaming does not have timestamp as offsets. Will see if I can do similar stuff here.

**Comment by itsvikramagr** [comment]
@OlhaShopback - Started a PR for this https://github.com/qubole/kinesis-sql/pull/49. Do you want to check it out?

**Comment by itsvikramagr** [comment]
Fixed as part of #49

**Comment by vishalgoel83** [comment]
might be using the same checkpointing folder in all streaming. By changing the path resolved my issue.

**Comment by sumitya** [comment]
[#49](https://github.com/qubole/kinesis-sql/pull/49) is not merged into the branch 3.0. which causes this issue to appear into branch 3.0, are we planning to merge the changes or creating a new branch 3.0-hotfix etc ?
