### ISSUE TITLE
Empty batches

### ISSUE THREAD

**Issue by ms32035** [qubole/kinesis-sql#38]
Is it normal for KinesisSource to generate empty microbatches when there is no new data in Kinesis? On Spark 2.4.0, when running a simple query with no trigger and console or CSV writer, a new batch is generated about every second. I remember that it wasn't the case with Kafka source.

**Comment by itsvikramagr** [comment]
@ms32035  - great that you brought this up. Your observation is in line with how this library is implemented. Unfortunately, Kinesis APIs and structured streaming requirements doesnt gel with each other too well. Then there are a few extra constraints with Kinesis. Elapsed time is also a dimension apart from actual data. 

As per the doc - https://docs.aws.amazon.com/kinesis/latest/APIReference/API_GetRecords.html

_The shard iterator specifies the position in the shard from which you want to start reading data records sequentially. If there are no records available in the portion of the shard that the iterator points to, GetRecords returns an empty list. It might take multiple calls to get to a portion of the shard that contains records._
 
So even though we don't have any new data, we generate empty micro-batch to always be on the tip of the stream. I have jotted down some of the design choices in this presentation - https://docs.google.com/presentation/d/1eSX7WiZxkjRy5ZDXAKRUDIKWqhP3ob2A1L1lat2QIXY/edit#slide=id.g34f0efcb5a_2_76 

Since streaming is a long running applications, I felt that generting empty micro-batch which can help in reducing future processing, when data is available, is acceptable.

Please feel free to work on the improvement and raise a PR. I would be happy to help you in reviewing the design doc and the code.

**Comment by ms32035** [comment]
Thanks @ms32035, will definitely look deeper into this, though I know quite little about Kinesis, so can't promise any outcome

**Comment by ms32035** [comment]
Ok, I get why you need a timestamp at the beginning,  but I see and approach that maybe(?) working. 
After an iterator runs out of record, there's a call to `describeShards` and the iterator is switched from `AFTER_SEQUENCE_NUMBER` to `AT_TIMESTAMP`

```
{
  "id" : "323a4926-4d03-4972-9bd0-c11911a2af8e",
  "runId" : "7c00cf0c-1983-4d4a-88b8-f851d16a2857",
  "name" : null,
  "timestamp" : "2019-01-14T11:02:09.424Z",
  "batchId" : 16,
  "numInputRows" : 0,
  "inputRowsPerSecond" : 0.0,
  "processedRowsPerSecond" : 0.0,
  "durationMs" : {
    "addBatch" : 232,
    "getBatch" : 2,
    "getOffset" : 1,
    "queryPlanning" : 6,
    "triggerExecution" : 295,
    "walCommit" : 28
  },
  "stateOperators" : [ ],
  "sources" : [ {
    "description" : "KinesisSource[Spark-dev]",
    "startOffset" : {
      "metadata" : {
        "streamName" : "Spark-dev",
        "batchId" : "15"
      },
      "shardId-000000000000" : {
        "iteratorType" : "AFTER_SEQUENCE_NUMBER",
        "iteratorPosition" : "49591930629841676863040294068075358744275408743001227266"
      }
    },
    "endOffset" : {
      "metadata" : {
        "streamName" : "Spark-dev",
        "batchId" : "16"
      },
      "shardId-000000000000" : {
        "iteratorType" : "AT_TIMESTAMP",
        "iteratorPosition" : "1547463729215"
      }
    },
    "numInputRows" : 0,
    "inputRowsPerSecond" : 0.0,
    "processedRowsPerSecond" : 0.0
  } ],
  "sink" : {
    "description" : "org.apache.spark.sql.execution.streaming.ConsoleSinkProvider@7f846314"
  }
}
```
Maybe getting `endingSequenceNumber` from `ListShards` and comparing it with the highest value from the last batch makes sense?

**Comment by itsvikramagr** [comment]
call to describeShards doesnt change the iterator type. DescribeShards is used only to check for re-sharding. You can increase the value of `kinesis.client.describeShardInterval` from 1s to say 1hr if re-sharding is not so frequent. 

ListShards is an alternative to DescribeShards to check for re-sharding and has more transaction limit. it can be a separate exercise to replace DescribeShards to ListShards but that is not relevant to your current issue.

the iterator does not switch from AFTER_SEQUENCE_NUMBER to AT_TIMESTAMP because of describeShards cal. it switches when it could not find any more records to process in the new batch and so it moves to the tip of the stream in timestamp. 

We can get endingSequenceNumber from ListShards (or DescribeShards) only when the shard is closed. This won't serve our purpose.

**Comment by ms32035** [comment]
> We can get endingSequenceNumber from ListShards (or DescribeShards) only when the shard is closed. This won't serve our purpose.
Well, this means I have no other better idea at the moment

**Comment by itsvikramagr** [comment]
@ms32035 - I have started a PR to handle this issue https://github.com/qubole/kinesis-sql/pull/49. Do you want to check that out?

**Comment by itsvikramagr** [comment]
We can use kinesis.client.avoidEmptyBatches as Source configuration to avoid empty batches. This will increase the time taken in the spark driver when it makes an API call to the kinesis connector to give a new batch.
